# Generated by Django 5.2.12 on 2026-03-09 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество попыток выполнения')),
                ('task_args', models.JSONField(blank=True, null=True, verbose_name='Аргументы запуска')),
                ('task_kwargs', models.JSONField(blank=True, null=True, verbose_name='Параметры запуска')),
                ('state', models.JSONField(blank=True, null=True, verbose_name='Состояние выполнения')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат выполнения')),
                ('profiling_cpu_result', models.TextField(blank=True, null=True, verbose_name='Результат профилирования CPU')),
                ('profiling_memory_result', models.TextField(blank=True, null=True, verbose_name='Результат профилирования ОЗУ')),
                ('task_id', models.UUIDField(unique=True, verbose_name='ID задачи')),
                ('restarted_task_id', models.UUIDField(blank=True, null=True, verbose_name='ID перезапущенной задачи')),
                ('task_name', models.CharField(verbose_name='Наименование задачи')),
                ('started_at', models.DateTimeField(verbose_name='Дата начала выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания выполнения')),
                ('duration', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Продолжительность выполнения задачи, сек')),
                ('task_status', models.CharField(choices=[('in_progress', 'Выполняется'), ('restarted', 'Перезапущено'), ('done', 'Завершена'), ('error', 'Ошибка выполнения'), ('REVOKED', 'Отозвана')], default='in_progress', max_length=50, verbose_name='Статус выполнения задачи')),
            ],
            options={
                'verbose_name': 'информация о выполнении задачи',
                'verbose_name_plural': 'Информация о выполнении задачи',
            },
        ),
        migrations.CreateModel(
            name='CeleryTaskRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "web_app.tasks.send_emails"', max_length=200, unique=True, verbose_name='Наименование задачи')),
                ('extra_settings', models.JSONField(blank=True, null=True, verbose_name='Настройки задачи')),
                ('enabled', models.BooleanField(default=True, verbose_name='Разрешена')),
                ('is_profiling_cpu', models.BooleanField(default=False, verbose_name='Доступно профилирование CPU')),
                ('is_profiling_memory', models.BooleanField(default=False, verbose_name='Доступно профилирование ОЗУ')),
            ],
            options={
                'verbose_name': 'Репозиторий задач',
                'verbose_name_plural': 'Репозиторий задач',
            },
        ),
        migrations.CreateModel(
            name='TaskBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='black', to='celery_monitoring.celerytaskrepository', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Черный список задач',
                'verbose_name_plural': 'Черный список задач',
            },
        ),
        migrations.CreateModel(
            name='TaskWhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='celery_monitoring.celerytaskrepository', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Белый список задач',
                'verbose_name_plural': 'Белый список задач',
            },
        ),
    ]
