from celery_misc import django_utils

CELERY_MISC_TRANSACTIONAL_OUTBOX = django_utils.import_from_settings('CELERY_MISC_TRANSACTIONAL_OUTBOX', default={})

SEND_EVENTS_MAX_RETRIES = CELERY_MISC_TRANSACTIONAL_OUTBOX.get('SEND_EVENTS_MAX_RETRIES', 5)
SEND_EVENTS_RETRY_BACKOFF = CELERY_MISC_TRANSACTIONAL_OUTBOX.get('SEND_EVENTS_RETRY_BACKOFF', 3)
SEND_EVENTS_RETRY_BACKOFF_MAX = CELERY_MISC_TRANSACTIONAL_OUTBOX.get('SEND_EVENTS_RETRY_BACKOFF_MAX', 600)
SEND_EVENTS_RETRY_JITTER = CELERY_MISC_TRANSACTIONAL_OUTBOX.get('SEND_EVENTS_RETRY_JITTER', True)
SEND_EVENTS_STRATEGY = CELERY_MISC_TRANSACTIONAL_OUTBOX.get(
    'SEND_EVENTS_STRATEGY', 'celery_misc.transactional_outbox.strategies.DummyBlockBatchStrategy'
)
