# Generated by Django 5.2.12 on 2026-03-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Idempotency key')),
                ('aggregate_type', models.CharField(help_text='Например, название модели данных "Order".', max_length=128, verbose_name='Тип агрегата')),
                ('aggregate_id', models.CharField(help_text='Например, ID экземпляра модели данных "164" или "8470df44-5e62-44db-8881-bfa9606b507c".', max_length=64, verbose_name='ID агрегата')),
                ('event_type', models.CharField(help_text='Например, "order.created".', max_length=128, verbose_name='Тип события')),
                ('payload', models.JSONField(verbose_name='Данные события')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('sent', 'Отправлено'), ('expired', 'Устарело'), ('failed', 'Ошибка отправки')], default='pending', max_length=50, verbose_name='Статус отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка отправки')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
