# Generated by Django 6.0.3 on 2026-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional_outbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxmessage',
            name='meta_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Метаданные события'),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='strategy',
            field=models.CharField(blank=True, help_text='Например, "celery_misc.transactional_outbox.strategies.DummyCheckStatusStrategy".', max_length=128, null=True, verbose_name='FQCN класса, реализующего стратегию отправки'),
        ),
    ]
