# Generated by Django 6.0.3 on 2026-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional_outbox', '0002_outboxmessage_meta_data_outboxmessage_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='idempotency_key',
            field=models.CharField(max_length=128, verbose_name='Idempotency key'),
        ),
    ]
